builds:
  - hooks:
      pre: go generate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image: perriea/tfversion
    tag_templates:
    - '{{ .Tag }}'
    - '{{ .Major }}.{{ .Minor }}'
    - 'latest'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
brew:
  github:
    owner: perriea
    name: homebrew-tap
  folder: Formula
  homepage:  https://aurelienperrier.com/tfversion
  description: Install Terraform binaries as fast and easily as possible
  test: |
    system "#{bin}/tfversion version"
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://aurelienperrier.com/tfversion
  description: Install Terraform binaries as fast and easily as possible
  maintainer: Aurelien Perrier <a.perrier89@gmail.com>
  license: MIT
  vendor: TfVersion
  formats:
    - deb
    - rpm
  recommends:
    - rpm