language: go

go:
  - 1.8.x
  - 1.9.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - go vet ./...
  - go get -u github.com/kardianos/govendor

script:
  - make test

notifications:
  email:
    recipients:
    - a.perrier89@gmail.com
    on_success: change
    on_failure: always