language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
  - mkdir -p ~/.tfversion/{tmp,bin}

script:
  - make test

notifications:
  email:
    recipients:
    - a.perrier89@gmail.com
    on_success: change
    on_failure: always